title:  Alumni Site - Turing School of Software and Design"
description: "Alumni site for Turing School of Software and Design"
url: "https://alumni-site.turing.edu/"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

plugins_dir:
  - jemoji
  - jekyll-algolia

algolia:
  index_name:     'alumni-site'
  extensions_to_index: 'html,md'
  nodes_to_index: 'p,li'
  settings:
    attributeForDistinct: 'title'
    distinct: true
  files_to_exclude:
    - _includes
    - _layouts
    - _plugins
    - _sass
    - _site
    - _templates
    - assets
    - public
    - stylesheets
